// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBkYV37FADW7fIXWUqj1yb4PEyeVaw1tiI',
    appId: '1:842028841222:web:cbf5cb99354d953fa70687',
    messagingSenderId: '842028841222',
    projectId: 'my-notes-dart-project',
    authDomain: 'my-notes-dart-project.firebaseapp.com',
    storageBucket: 'my-notes-dart-project.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAPgzX1rOBaqENqJCpLQboYY5kUqH6pvzU',
    appId: '1:842028841222:android:937222a4257a7b4ea70687',
    messagingSenderId: '842028841222',
    projectId: 'my-notes-dart-project',
    storageBucket: 'my-notes-dart-project.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAj7OBqXLNFCbFegiy6PnXPcWVefEma5lg',
    appId: '1:842028841222:ios:73cc9376f35e4e46a70687',
    messagingSenderId: '842028841222',
    projectId: 'my-notes-dart-project',
    storageBucket: 'my-notes-dart-project.appspot.com',
    iosClientId: '842028841222-0dl67feuuhcn09p6q96opktrt1jmkjeh.apps.googleusercontent.com',
    iosBundleId: 'in.ASE.myNotes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAj7OBqXLNFCbFegiy6PnXPcWVefEma5lg',
    appId: '1:842028841222:ios:73cc9376f35e4e46a70687',
    messagingSenderId: '842028841222',
    projectId: 'my-notes-dart-project',
    storageBucket: 'my-notes-dart-project.appspot.com',
    iosClientId: '842028841222-0dl67feuuhcn09p6q96opktrt1jmkjeh.apps.googleusercontent.com',
    iosBundleId: 'in.ASE.myNotes',
  );
}
